---
apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
    - name: fluentd-config
      configMap:
        name: fluentd
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
    - name: fluentd
      image: fluent/fluentd:v1.11-1
      volumeMounts:
        - name: shared-logs
          mountPath: /logs
        - name: fluentd-config
          mountPath: /fluentd/etc
