---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-pod
spec:
  containers:
    - name: liveness-probe-pod
      image: nginx
      livenessProbe:
        exec:
          command:
            - /bin/bash
            - -c
            - "exit 1"
        initialDelaySeconds: 5
        periodSeconds: 5
