---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: readiness-deployment
  template:
    metadata:
      labels:
        app: readiness-deployment
    spec:
      containers:
        - name: readiness-probe-pod
          image: mhausenblas/simpleservice:0.4.0
          ports:
            - containerPort: 9876
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "exit 1"
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-service
spec:
  ports:
    - port: 80
      targetPort: 9876
  selector:
    app: readiness-deployment
