---
apiVersion: v1
kind: Pod
metadata:
  name: ram-limits
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        requests:
          memory: 100M
        limits:
          memory: 100M
      command: ["stress"]
      args:
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "200M"
        - "--verbose"
        - "--vm-hang"
        - "1"
